import { formatINR } from "../utils/money";

export default function ReportView({
    month,
    year,
    user,
    income = [],
    needs = [],
    wants = [],
    savings = [],
    debt = [],
}) {
    const totalIncome = income.reduce((s, i) => s + (i.actual || 0), 0);

    const totalNeeds = needs.reduce((s, n) => s + (n.actual || 0), 0);
    const totalWants = wants.reduce((s, w) => s + (w.actual || 0), 0);
    const totalExpenses = totalNeeds + totalWants;

    const totalSaved = savings.reduce((s, g) => s + (g.saved || 0), 0);

    const totalDebt = debt.reduce(
        (s, d) => s + Math.max((d.balance || 0) - (d.paid || 0), 0),
        0
    );

    const netWorth = totalIncome + totalSaved - totalDebt;

    return (
        <div style={styles.page}>
            {/* ================= HEADER ================= */}
            <h1 style={styles.title}>exPtrack</h1>
            <p style={styles.subtitle}>Personal Finance Report</p>

            <div style={styles.meta}>
                <span><b>Month:</b> {month} {year}</span>
                <span><b>User:</b> {user}</span>
            </div>

            <hr />

            {/* ================= EXECUTIVE SUMMARY ================= */}
            <h2 style={styles.sectionTitle}>Executive Summary</h2>

            <div style={styles.kpiRow}>
                <KPI label="Total Income" value={formatINR(totalIncome)} />
                <KPI label="Total Spent" value={formatINR(totalExpenses + totalSaved)} />
                <KPI label="Net Worth" value={formatINR(netWorth)} />
            </div>

            <p style={styles.insight}>
                This month, you spent{" "}
                <b>{Math.round(((totalExpenses + totalSaved) / totalIncome) * 100)}%</b>{" "}
                of your income. Your net worth is{" "}
                <b>{netWorth >= 0 ? "positive" : "negative"}</b>, mainly due to outstanding
                debt obligations.
            </p>

            {/* ================= CASH FLOW ================= */}
            <h2 style={styles.sectionTitle}>Cash Flow Summary</h2>

            <Table
                rows={[
                    ["Total Income", formatINR(totalIncome)],
                    ["Total Expenses", formatINR(totalExpenses)],
                    ["Total Savings", formatINR(totalSaved)],
                    ["Debt Outstanding", formatINR(totalDebt)],
                    ["Net Worth", formatINR(netWorth)],
                ]}
            />

            {/* ================= INCOME ================= */}
            <h2 style={styles.sectionTitle}>Income</h2>
            <Table
                header={["Source", "Expected", "Actual"]}
                rows={income.map((i) => [
                    i.name,
                    formatINR(i.expected),
                    formatINR(i.actual),
                ])}
            />

            {/* ================= NEEDS ================= */}
            <h2 style={styles.sectionTitle}>Essential Expenses (Needs)</h2>
            <Table
                header={["Name", "Budget", "Actual"]}
                rows={needs.map((n) => [
                    n.name,
                    formatINR(n.budget),
                    formatINR(n.actual),
                ])}
                footer={["Total", "", formatINR(totalNeeds)]}
            />

            {/* ================= WANTS ================= */}
            <h2 style={styles.sectionTitle}>Discretionary Spending (Wants)</h2>
            <Table
                header={["Name", "Budget", "Actual"]}
                rows={wants.map((w) => [
                    w.name,
                    formatINR(w.budget),
                    formatINR(w.actual),
                ])}
                footer={["Total", "", formatINR(totalWants)]}
            />

            {/* ================= SAVINGS ================= */}
            <h2 style={styles.sectionTitle}>Savings Goals</h2>
            <Table
                header={["Goal", "Target", "Saved", "Remaining"]}
                rows={savings.map((s) => [
                    s.name,
                    formatINR(s.goal),
                    formatINR(s.saved),
                    formatINR(s.goal - s.saved),
                ])}
            />

            {/* ================= DEBT ================= */}
            <h2 style={styles.sectionTitle}>Outstanding Debt</h2>
            <Table
                header={["Loan", "Total", "Paid", "Remaining"]}
                rows={debt.map((d) => [
                    d.name,
                    formatINR(d.balance),
                    formatINR(d.paid),
                    formatINR(d.balance - d.paid),
                ])}
                footer={["Total Debt", "", "", formatINR(totalDebt)]}
            />

            <p style={styles.footer}>
                Generated by exPtrack • Confidential Financial Report
            </p>
        </div>
    );
}

/* ================= SMALL COMPONENTS ================= */

function KPI({ label, value }) {
    return (
        <div style={styles.kpi}>
            <div style={styles.kpiLabel}>{label}</div>
            <div style={styles.kpiValue}>{value}</div>
        </div>
    );
}

function Table({ header, rows, footer }) {
    return (
        <table style={styles.table}>
            {header && (
                <thead>
                    <tr>
                        {header.map((h) => (
                            <th key={h} style={styles.th}>{h}</th>
                        ))}
                    </tr>
                </thead>
            )}
            <tbody>
                {rows.map((r, i) => (
                    <tr key={i}>
                        {r.map((c, j) => (
                            <td key={j} style={styles.td}>{c}</td>
                        ))}
                    </tr>
                ))}
            </tbody>
            {footer && (
                <tfoot>
                    <tr>
                        {footer.map((f, i) => (
                            <td key={i} style={styles.tdBold}>{f}</td>
                        ))}
                    </tr>
                </tfoot>
            )}
        </table>
    );
}

/* ================= PDF-SAFE STYLES ================= */

const styles = {
    page: {
        fontFamily: "Arial, sans-serif",
        fontSize: 12,
        color: "#000",
        padding: 40,
    },
    title: {
        fontSize: 26,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 4,
    },
    subtitle: {
        textAlign: "center",
        marginBottom: 20,
    },
    meta: {
        display: "flex",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    sectionTitle: {
        marginTop: 30,
        marginBottom: 10,
        fontSize: 16,
        fontWeight: "bold",
    },
    kpiRow: {
        display: "flex",
        justifyContent: "space-between",
        margin: "20px 0",
    },
    kpi: {
        border: "1px solid #ccc",
        padding: 12,
        width: "30%",
        textAlign: "center",
    },
    kpiLabel: {
        fontSize: 11,
        marginBottom: 4,
    },
    kpiValue: {
        fontSize: 16,
        fontWeight: "bold",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        marginBottom: 20,
    },
    th: {
        borderBottom: "1px solid #999",
        textAlign: "left",
        padding: 6,
    },
    td: {
        borderBottom: "1px solid #ddd",
        padding: 6,
    },
    tdBold: {
        padding: 6,
        fontWeight: "bold",
        borderTop: "2px solid #000",
    },
    insight: {
        marginTop: 10,
        marginBottom: 20,
    },
    footer: {
        textAlign: "center",
        marginTop: 40,
        fontSize: 10,
    },
};
