import { formatINR } from "../utils/money";

export default function ReportView({
    month,
    year,
    user,
    income,
    needs,
    wants,
    savings,
    debt,
    kpis,
}) {
    return (
        <div
            id="pdf-root"
            className="pdf-root text-[11px] text-gray-900 leading-relaxed bg-white max-w-[210mm] mx-auto p-6"
        >
            {/* ================= HEADER ================= */}
            <header className="flex justify-between items-start border-b pb-4 mb-6">
                <div>
                    <h1 className="text-2xl font-semibold tracking-tight">exPtrack</h1>
                    <p className="text-[11px] text-gray-500 mt-1">
                        Monthly Financial Summary
                    </p>
                </div>

                <div className="text-right text-[10px] space-y-1">
                    <div className="font-semibold text-[11px]">
                        {month} {year}
                    </div>
                    <div className="text-gray-500">Prepared for: <span className="font-medium">{user}</span></div>
                    <div className="text-gray-400">Generated by exPtrack</div>
                </div>
            </header>

            {/* ================= OVERVIEW STRIP ================= */}
            <section className="mb-6">
                <h2 className="text-[10px] font-semibold uppercase tracking-wide text-gray-500 mb-3">
                    Overview · This month
                </h2>
                <div className="grid grid-cols-2 gap-3 mb-4">
                    <KPI
                        label="Total income"
                        value={kpis.totalIncome}
                        tone="positive"
                        hint="All income actually received this month"
                    />
                    <KPI
                        label="Total spent"
                        value={kpis.totalSpent}
                        tone="neutral"
                        hint="Needs, wants, savings and debt payments"
                    />
                    <KPI
                        label="Total savings"
                        value={kpis.totalSavings}
                        tone={kpis.totalSavings > 0 ? "positive" : "warning"}
                        hint={kpis.totalSavings > 0 ? "Amount set aside this month" : "No savings recorded"}
                    />
                    <KPI
                        label="Net worth impact"
                        value={kpis.netWorth}
                        tone={kpis.netWorth >= 0 ? "positive" : "negative"}
                        highlight={kpis.netWorth < 0}
                        hint={kpis.netWorth < 0 ? "Net position decreased this month" : "Net position improved this month"}
                    />
                </div>

                <div className="rounded-md border border-gray-200 bg-gray-50 px-3 py-2 text-[10px] text-gray-700">
                    <span>
                        You allocated{" "}
                        <span className="font-semibold">{kpis.incomeAllocatedPct}%</span> of your income this month.&nbsp;
                    </span>
                    {kpis.netWorth < 0 ? (
                        <span>
                            Your <span className="font-semibold text-red-600">net worth decreased</span>, driven mainly by outstanding debt.
                        </span>
                    ) : (
                        <span>
                            Your <span className="font-semibold text-green-600">net worth improved</span> compared to your liabilities.
                        </span>
                    )}
                </div>
            </section>

            {/* ================= CASH FLOW SNAPSHOT ================= */}
            <section className="mb-8">
                <h2 className="text-[10px] font-semibold uppercase tracking-wide text-gray-500 mb-2">
                    Cash flow snapshot
                </h2>
                <div className="grid grid-cols-2 gap-3">
                    <KeyValue label="Total income" value={kpis.totalIncome} />
                    <KeyValue
                        label="Needs + wants"
                        value={kpis.needsActual + kpis.wantsActual}
                    />
                    <KeyValue label="Savings this month" value={kpis.totalSavings} />
                    <KeyValue label="Debt outstanding" value={kpis.totalDebt} />
                </div>
            </section>

            {/* PAGE BREAK */}
            <PageBreak />

            {/* ================= INCOME ================= */}
            <Section title="Income">
                <Table
                    headers={["Source", "Expected", "Actual"]}
                    rows={income.map((i) => [
                        i.name,
                        formatINR(i.expected),
                        formatINR(i.actual),
                    ])}
                />
            </Section>

            {/* ================= NEEDS ================= */}
            <Section title="Essential expenses (needs)">
                <Table
                    headers={["Name", "Budget", "Actual"]}
                    rows={needs.map((n) => [
                        n.name,
                        formatINR(n.budget),
                        formatINR(n.actual),
                    ])}
                    footer={["Total", "", formatINR(kpis.needsActual)]}
                />
            </Section>

            {/* ================= WANTS ================= */}
            <Section title="Discretionary spending (wants)">
                <Table
                    headers={["Name", "Budget", "Actual"]}
                    rows={wants.map((w) => [
                        w.name,
                        formatINR(w.budget),
                        formatINR(w.actual),
                    ])}
                    footer={["Total", "", formatINR(kpis.wantsActual)]}
                />
            </Section>

            <PageBreak />

            {/* ================= SAVINGS ================= */}
            <Section title="Savings goals">
                <Table
                    headers={["Goal", "Target", "Saved", "Remaining"]}
                    rows={savings.map((s) => [
                        s.name,
                        formatINR(s.goal),
                        formatINR(s.saved),
                        formatINR(s.goal - s.saved),
                    ])}
                />
            </Section>

            {/* ================= DEBT ================= */}
            <Section title="Outstanding debt">
                <Table
                    headers={["Loan", "Total", "Paid", "Remaining"]}
                    rows={debt.map((d) => [
                        d.name,
                        formatINR(d.balance),
                        formatINR(d.paid),
                        formatINR(d.balance - d.paid),
                    ])}
                    footer={["Total Debt", "", "", formatINR(kpis.totalDebt)]}
                />
            </Section>

            {/* ================= RECOMMENDATIONS ================= */}
            <Section title="Insights & recommendations">
                <ul className="list-disc pl-5 text-[11px] space-y-1.5">
                    {kpis.netWorth < 0 && (
                        <li>
                            Focus on reducing high-interest debt to improve net
                            worth.
                        </li>
                    )}
                    {kpis.incomeAllocatedPct > 60 && (
                        <li>
                            Your spending is relatively high. Consider increasing
                            savings allocation.
                        </li>
                    )}
                    {kpis.totalSavings === 0 && (
                        <li>
                            Start building an emergency fund covering at least 3–6
                            months of expenses.
                        </li>
                    )}
                </ul>
            </Section>

            {/* ================= FOOTER ================= */}
            <footer className="mt-10 pt-3 border-t text-[9px] text-center text-gray-400">
                exPtrack · Personal finance dashboard · Confidential
            </footer>
        </div>
    );
}

/* ================= HELPERS ================= */

function KPI({ label, value, tone = "neutral", highlight, hint }) {
    const toneClasses = {
        positive: "border-emerald-200 bg-emerald-50",
        negative: "border-red-200 bg-red-50",
        warning: "border-amber-200 bg-amber-50",
        neutral: "border-gray-200 bg-gray-50",
    };

    const textTone =
        tone === "positive"
            ? "text-emerald-700"
            : tone === "negative"
                ? "text-red-700"
                : tone === "warning"
                    ? "text-amber-700"
                    : "text-gray-700";

    return (
        <div className={`rounded-md border px-3 py-2 ${toneClasses[tone]} min-h-[52px]`}>
            <div className="text-[10px] text-gray-600 mb-0.5">{label}</div>
            <div
                className={`text-[13px] font-semibold ${highlight ? "text-red-600" : textTone
                    }`}
            >
                {formatINR(value)}
            </div>
            {hint && (
                <div className="mt-0.5 text-[9px] text-gray-500 leading-snug">
                    {hint}
                </div>
            )}
        </div>
    );
}

function Section({ title, children }) {
    return (
        <section className="mb-7">
            <h2 className="text-[10px] font-semibold uppercase tracking-wide mb-2 text-gray-600">
                {title}
            </h2>
            {children}
        </section>
    );
}

function KeyValue({ label, value, bold }) {
    return (
        <div className="flex justify-between py-1.5 border-b last:border-0 text-[11px]">
            <span className="text-gray-600">{label}</span>
            <span className={bold ? "font-semibold" : "text-gray-800"}>
                {formatINR(value)}
            </span>
        </div>
    );
}

function Table({ headers, rows, footer }) {
    return (
        <table className="w-full border-collapse text-[11px]">
            <thead>
                <tr className="border-b bg-gray-50">
                    {headers.map((h) => (
                        <th
                            key={h}
                            className="text-left font-semibold py-2 px-2 text-gray-700 text-[10px]"
                        >
                            {h}
                        </th>
                    ))}
                </tr>
            </thead>
            <tbody>
                {rows.map((row, i) => (
                    <tr
                        key={i}
                        className={`border-b last:border-0 ${i % 2 === 0 ? "bg-white" : "bg-gray-50"
                            }`}
                    >
                        {row.map((cell, j) => (
                            <td
                                key={j}
                                className={`py-1.5 px-2 ${j === 0 ? "text-left" : "text-right font-medium"
                                    }`}
                            >
                                {cell}
                            </td>
                        ))}
                    </tr>
                ))}
            </tbody>
            {footer && (
                <tfoot>
                    <tr className="border-t font-semibold bg-gray-100">
                        {footer.map((f, i) => (
                            <td key={i} className="py-2 px-2 text-right">
                                {f}
                            </td>
                        ))}
                    </tr>
                </tfoot>
            )}
        </table>
    );
}

function PageBreak() {
    return <div className="page-break my-8" />;
}
